# Generated by Django 4.2.5 on 2023-11-03 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.courses'),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.exam'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.city'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.country'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principle.courses'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.state'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.country'),
        ),
        migrations.AddField(
            model_name='room',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.courses'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.state'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.courses'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.student'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicdetail',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.courses'),
        ),
        migrations.AddField(
            model_name='academicdetail',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.exam'),
        ),
        migrations.AddField(
            model_name='academicdetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.student'),
        ),
        migrations.AddField(
            model_name='academicdetail',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principle.subject'),
        ),
    ]
